# Generated by Django 5.0.3 on 2024-05-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('availability', models.IntegerField(null=True)),
                ('categories', models.ManyToManyField(related_name='products_categories', to='products.categories')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['name', 'availability'],
            },
        ),
    ]
