# Generated by Django 5.0.3 on 2024-05-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('user', models.ManyToManyField(related_name='user', to='authentification.customuser')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status', to='order.orderstatus')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
